# Where should we write the GIF?
Output mfp.gif

Set FontSize 23
Set Margin 5
Set MarginFill "#8b9bf7"
Set BorderRadius 10
Set Width 2300
Set Height 1200
Set Theme "TokyoNightStorm"

Type@300ms "mfp"
Sleep 1s
Enter
Sleep 2s
Type@220ms "jjjjjjjjjjjjjjjjjkkk"
Sleep 1s
Enter
Space
Sleep 2s
Type "?"
Sleep 5s
Type o
Type "llll"
Sleep 2s
Type "/"
Sleep 2s
Type d
Sleep 1s
Type og
Sleep 1s
Enter
Enter
Sleep 5s
Space
Type "q"
